// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbe_k4UAHMtXS1k7Ob33Hujz6AfhEGqro',
    appId: '1:1017603697734:android:07c935d7174ea0fba9ae47',
    messagingSenderId: '1017603697734',
    projectId: 'eldercare-5cc0d',
    databaseURL: 'https://eldercare-5cc0d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'eldercare-5cc0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdxvdPSyuGttyLnTnb5ckJMlPzJHkMb8k',
    appId: '1:1017603697734:ios:a1513d93f5d904a1a9ae47',
    messagingSenderId: '1017603697734',
    projectId: 'eldercare-5cc0d',
    databaseURL: 'https://eldercare-5cc0d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'eldercare-5cc0d.appspot.com',
    iosBundleId: 'it.univpm.elderCare',
  );
}
